### ISSUE TITLE
Could not find client for frigate instance id: frigate

### ISSUE THREAD

**Issue by baldisos** [dermotduffy/advanced-camera-card#114]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v2.1.0

**Last working release (if known):**
1.1.0

**Frigate Version:**
0.9.1

**Browser and Operating System:**
Not related to Browser / OS.

**Description of problem:**
After Update to Version v.2.1.0 the card does show:
```
Could not find client for frigate instance id: frigate. Check troubleshooting .
```
under Clips and Snapshots.

The Log also says:
```
2021-10-10 20:01:22 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472963835360] Error handling message: Could not find client for frigate instance id: frigate
```

This did work before, so it isn't related to the id. I haven't changed the config since then, so the id has been always at the default "frigate" value.

**Comment by dermotduffy** [comment]
Hmm, haven't encountered this before on the card.

That's a log message from the underlying [integration](https://github.com/blakeblackshear/frigate-hass-integration/blob/master/custom_components/frigate/media_source.py#L527), so I'd suspect this isn't an issue with the card but with how the integration and your Frigate backend are talking.

So lets forget about the card for a moment.

Does media browsing work for you through the 'Media Browser' sidepanel button in HA? How many Frigate servers do you have setup? Can you paste the `mqtt` section of your Frigate server config?
