### ISSUE TITLE
Support for custom still image from url as default view

### ISSUE THREAD

**Issue by ronschaeffer** [dermotduffy/advanced-camera-card#124]
Fantastic work on this card. Thank you.

Following on from the [addition of elements](https://github.com/dermotduffy/frigate-hass-card/issues/77) as are available with the [Picture Elements Card](https://www.home-assistant.io/lovelace/picture-elements/), I'd like to request support for a still image as the default view, similar to the image option on the Picture Elements card.

The idea is to show a still image underneath the menu overlay instead of jumping directly into live, clips, snapshots, etc.  An example use case would be when the live stream of a camera normally takes some time to start when switching dashboard views. The "broken file" icon or spinner in the video player shown when the stream is not ready could be distracting, but you may not want to immediately display clips or a snapshot. For example, you may have switched dashboard views to interact with something other than the camera card.

A possible configuration:
 
```
type: custom:frigate-card
camera_entity: camera.bedroom
view_default: image
  image_url: https://demo.home-assistant.io/stub_config/bedroom.png
```

**Comment by dermotduffy** [comment]
OK -- added to the list. Few other things I want to work on first, but leave it with me to play around with the idea and see if I can get something workable.
