### ISSUE TITLE
Unable to find Frigate instance with ID: frigate (after upgrade to 2023.11)

### ISSUE THREAD

**Issue by thomaspalmdk** [dermotduffy/advanced-camera-card#1317]
Does anyone know why this is happening after 2023.11? I just upgraded yesterday.
I did not change the ID of Frigate.
Where should I start my investigation?

```json
{
  "request": {
    "type": "frigate/events/get",
    "instance_id": "frigate",
    "cameras": [
      "camera_1"
    ],
    "limit": 50,
    "id": 46
  },
  "response": {
    "code": "not_found",
    "message": "Unable to find Frigate instance with ID: frigate"
  }
}
```

**Comment by dermotduffy** [comment]
Guess: Issue not related to the card, but your Frigate integration is not working correctly. Check your Home Assistant logs, and/or reinstall the integration?
