### ISSUE TITLE
Frigate Proxy

### ISSUE THREAD

**Issue by KenwoodFox** [dermotduffy/advanced-camera-card#1371]
**Checklist:**

- [x] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
`v2.5.0`

**Last working release (if known):**
`n\a`

**Browser and Operating System:**
`Firefox`, `Arch Linux`

**Description of problem:**

Getting the error `Failed to receive response from Home Assistant for request.` when trying to put in camera for frigate proxy (3.0.x)

![image](https://github.com/dermotduffy/frigate-hass-card/assets/31870999/f69da366-9524-4aaf-ba13-45280b40d142)

**Frigate card diagnostic information**

```json
{
  "ha_version": "2024.2.1",
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0",
  "date": "2024-02-14T16:30:33.134Z",
  "frigate_version": {},
  "lang": "en",
  "timezone": "America/New_York",
  "git": {
    "build_version": "5.2.0-HEAD+g69249b6",
    "build_date": "Fri, 23 Jun 2023 15:26:26 GMT",
    "commit_date": "Thu, 22 Jun 2023 09:21:26 -0600"
  },
  "config": {
    "type": "custom:frigate-card",
    "cameras": [
      {
        "camera_entity": "camera.octoprint_camera"
      },
      {
        "frigate": {
          "camera_name": "front_door",
          "url": "http://10.85.3.22:5000/"
        }
      }
    ]
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

Thats everything i can think of! I noticed it said it only used the URL for a button so.. maybe this is an issue with my config not having HA restream cameras from frigate?

**Comment by dermotduffy** [comment]
>  "frigate_version": {},

... do you have the [Frigate integration](https://github.com/blakeblackshear/frigate-hass-integration) installed?

**Comment by KenwoodFox** [comment]
> > "frigate_version": {},
> 
> ... do you have the [Frigate integration](https://github.com/blakeblackshear/frigate-hass-integration) installed?

Sorry, the integration version is `1.4` and im using Frigate version `0.13.1`

**Comment by dermotduffy** [comment]
> Sorry, the integration version is 1.4 and im using Frigate version 0.13.1

The diagnostics hint that you do not have it installed at all, or at least the card cannot find it. The most recent version is [v5.0.1](https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v5.0.1) . When you say `1.4` could you be referring to the version of something else?

When you go here, can you see Frigate:

`https://YOUR_HA_INSTANCE/config/integrations/dashboard`

**Comment by KenwoodFox** [comment]
> https://YOUR_HA_INSTANCE/config/integrations/dashboard

Oh! no I dont see it as an integration i only see it in the add-ons tab

![image](https://github.com/dermotduffy/frigate-hass-card/assets/31870999/0942cbcd-d930-479f-ace9-cf1339eb4e6b)

**Comment by KenwoodFox** [comment]
That did it, so sorry
